version: "3.9"
services:
  react-front:
    # image: "front"
    build: services/reactapp
    ports:
      - "80:3000"
    networks:
      - main
  back-end:
    image: "backend"
    ports:
      - 6015:6015
    networks:
      - main

networks:
  main: 